### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by carloscolbe** [carloscolmenarez/url-to-json#1]
## TO-DO LIST:
- [x] Move URL to JSON Parser to the top.
- [ ] Separate functionality in Vue components.
- [ ] Dark mode / light mode switch.
- [x] Check icon instead of alert on copy.
